name: Release

on:
  repository_dispatch:
    types: [cloudtrail-watcher-release]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update semantic version
        run: |
          sed -i 's/semantic_version = "[^"]*"/semantic_version = "${{ github.event.client_payload.version }}"/' main.tf

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add main.tf
          git commit -m "Update version to ${{ github.event.client_payload.version }}"
          git push

      - name: Create tag
        run: |
          git tag ${{ github.event.client_payload.version }}
          git push origin ${{ github.event.client_payload.version }}

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.client_payload.version }}
          release_name: ${{ github.event.client_payload.version }}
          draft: false
          prerelease: false